name: dollfind
description: A private pocket curator for collectible toys and dolls. Made for Silje, by Geir Erik.
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  http: ^1.2.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  uuid: ^4.4.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/identification_tips_dolls.md
